- name: Install Zabbix Agent
  hosts: all
  become: true

  vars:
    zabbix_server: "192.168.161.131"

  tasks:

    - name: Download repository package
      get_url:
        url: https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.0+ubuntu24.04_all.deb
        dest: /tmp/zabbix-release.deb

    - name: Install repository
      apt:
        deb: /tmp/zabbix-release.deb

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install zabbix-agent2
      apt:
        name: zabbix-agent2
        state: present

    - name: Configure Server
      replace:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: '^Server=.*'
        replace: "Server={{ zabbix_server }}"

    - name: Configure Active Server
      replace:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: '^ServerActive=.*'
        replace: "ServerActive={{ zabbix_server }}"

    - name: Configure Hostname
      replace:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: '^Hostname=.*'
        replace: "Hostname={{ inventory_hostname }}"

    - name: Enable Agent
      service:
        name: zabbix-agent2
        state: restarted
        enabled: yes
