- name: Install NGINX on target VM
  hosts: all
  become: yes

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Ensure nginx is running
      service:
        name: nginx
        state: started
        enabled: yes
